### ISSUE TITLE
Wrong Rethrowing of the Exception?

### ISSUE THREAD

**Issue by DerAlbertCom** [twenzel/Demystify.Everything#9]
https://github.com/twenzel/Demystify.Everything/blob/3f93ca386f0e11200f5914e10deab596eb8108da/src/codeessentials.AspNetCore.Diagnostics.Demystifier/ExceptionHandlerMiddleware.cs#L45

I think this should be  `ExceptionDispatchInfo.Capture(exc).Throw();`, so that the Stacktrace is kept.

**Comment by twenzel** [comment]
Because it's all within the catch-block and so we don't leave the scope of this exception, we're fine using just `throw`. If we would save the exception to a variable and trying to re-throw it later, than your remark is correct and we should use the `ExceptionDispatchInfo` class.
More explanation : http://derpturkey.com/preserving-a-stacktrace-when-rethrowing-exception-with-exceptiondispatchinfo/

Alternatively I can rewrite as you recommended, but it has the same effect.

**Comment by DerAlbertCom** [comment]
Nitty gritty details. Thanks for Headsup.
